### ISSUE TITLE
is it for 1.21?

### ISSUE THREAD

**Issue by Legendmanj** [0PandaDEV/SharedBackpacks#2]
can this be used for 1.21?

**Comment by 0PandaDEV** [comment]
I didnt updated the dependencies yet but it should work if not let me know

**Comment by Legendmanj** [comment]
> I didnt updated the dependencies yet but it should work if not let me know

WAIt, this is a plugin? i thought it was a fabric mod 
mb );

**Comment by 0PandaDEV** [comment]
:)
